### ISSUE TITLE
Style suggestion

### ISSUE THREAD

**Issue by lruanova** [barbarabrito/haikaidodia#1]
Hey. I was thinking maybe another font and a background image could be cool. Something like:

```
@import url('https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap');

html{
	background-image: url("https://image.freepik.com/free-vector/hand-painted-background-mountain-landscape_1048-8362.jpg"); /* The image used */
  	  background-repeat: no-repeat;
  	  background-size: cover 	;
	font-family: 'Yuji Syuku', serif;
		
}
```

![haiku](https://user-images.githubusercontent.com/64481800/141704881-70eb05bf-daeb-45e3-8133-fa666e880acd.png)

**Comment by barbarabrito** [comment]
> Hey. I was thinking maybe another font and a background image could be cool. Something like:
> 
> ```
> @import url('https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap');
> 
> html{
> 	background-image: url("https://image.freepik.com/free-vector/hand-painted-background-mountain-landscape_1048-8362.jpg"); /* The image used */
>   	  background-repeat: no-repeat;
>   	  background-size: cover 	;
> 	font-family: 'Yuji Syuku', serif;
> 		
> }
> ```
> 
> ![haiku](https://user-images.githubusercontent.com/64481800/141704881-70eb05bf-daeb-45e3-8133-fa666e880acd.png)

I was thinking about adding a background but at the same time I kind of like the white background as it is because it reminds me of a book page.

**Comment by lruanova** [comment]
Maybe something like:
```

@import url('https://fonts.googleapis.com/css?family=Raleway');
@import url('https://fonts.googleapis.com/css2?family=Yuji+Syuku&display=swap');

html{
	background-image: url("https://images.unsplash.com/photo-1586075010923-2dd4570fb338?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80"); /* The image used */
  	  background-repeat: no-repeat;
  	  background-size: cover 	;
		font-family: 'Yuji Syuku', serif;
}
```

![haiku](https://user-images.githubusercontent.com/64481800/142014712-b03f7bbc-c4bd-4c8c-a369-8c9922b66aa9.png)

Dont want to change your idea, its just a style suggestion, sorry if you dont want to change it i dont want to alter your work
